service: newrelic-lambda-layers-nodejs-example

provider:
  name: aws
  stage: prod
  region: us-east-1
  stackTags:
    environment: us-testing
    owning_team: LAMBDA
    product: aws-lambda
  tags:
    environment: us-testing
    owning_team: LAMBDA
    product: aws-lambda

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    logLevel: debug

functions:
  layer-nodejs16x:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.js
    runtime: nodejs16.x

  layer-nodejs18x:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.js
    runtime: nodejs18.x

  layer-nodejs20x:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.js
    runtime: nodejs20.x

  layer-nodejs22x:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.js
    runtime: nodejs22.x
